<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Characters" Member="Characters">
    <Type Name="Character">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Race" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Experience" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[User]" Member="User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Character" Member="User1" ThisKey="User" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Class_Character" Member="Class1" ThisKey="Class" OtherKey="Id" Type="Class" IsForeignKey="true" />
      <Association Name="Race_Character" Member="Race1" ThisKey="Race" OtherKey="Id" Type="Race" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Character" Member="Characters" ThisKey="Id" OtherKey="User" Type="Character" />
    </Type>
  </Table>
  <Table Name="dbo.Classes" Member="Classes">
    <Type Name="Class">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MainStat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Class_Character" Member="Characters" ThisKey="Id" OtherKey="Class" Type="Character" />
      <Association Name="Class_ClassesStat" Member="ClassesStats" ThisKey="Id" OtherKey="Class" Type="ClassesStat" />
    </Type>
  </Table>
  <Table Name="dbo.ClassesStats" Member="ClassesStats">
    <Type Name="ClassesStat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Class" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Stat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Class_ClassesStat" Member="Class1" ThisKey="Class" OtherKey="Id" Type="Class" IsForeignKey="true" />
      <Association Name="Stat_ClassesStat" Member="Stat1" ThisKey="Stat" OtherKey="Id" Type="Stat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ItemSlot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="CurrencyValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Item_itemsStat" Member="itemsStats" ThisKey="Id" OtherKey="Item" Type="itemsStat" />
      <Association Name="ItemSlot_Item" Member="ItemSlot1" ThisKey="ItemSlot" OtherKey="Id" Type="ItemSlot" IsForeignKey="true" />
      <Association Name="ItemType_Item" Member="ItemType1" ThisKey="ItemType" OtherKey="Id" Type="ItemType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemSlots" Member="ItemSlots">
    <Type Name="ItemSlot">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Slot" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ItemSlot_Item" Member="Items" ThisKey="Id" OtherKey="ItemSlot" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.ItemTypes" Member="ItemTypes">
    <Type Name="ItemType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ItemType_Item" Member="Items" ThisKey="Id" OtherKey="ItemType" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Races" Member="Races">
    <Type Name="Race">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="Race_Character" Member="Characters" ThisKey="Id" OtherKey="Race" Type="Character" />
    </Type>
  </Table>
  <Table Name="dbo.StatTypes" Member="StatTypes">
    <Type Name="StatType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="StatType_Stat" Member="Stats" ThisKey="Id" OtherKey="StatType" Type="Stat" />
    </Type>
  </Table>
  <Table Name="dbo.Stats" Member="Stats">
    <Type Name="Stat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StatType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Stat_ClassesStat" Member="ClassesStats" ThisKey="Id" OtherKey="Stat" Type="ClassesStat" />
      <Association Name="Stat_itemsStat" Member="itemsStats" ThisKey="Id" OtherKey="Stat" Type="itemsStat" />
      <Association Name="StatType_Stat" Member="StatType1" ThisKey="StatType" OtherKey="Id" Type="StatType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.itemsStats" Member="itemsStats">
    <Type Name="itemsStat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Item" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Stat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_itemsStat" Member="Item1" ThisKey="Item" OtherKey="Id" Type="Item" IsForeignKey="true" />
      <Association Name="Stat_itemsStat" Member="Stat1" ThisKey="Stat" OtherKey="Id" Type="Stat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Levels" Member="Levels">
    <Type Name="Level">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Experience" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>